### ISSUE TITLE
LipUI的部分思路改进和UI设计改进

### ISSUE THREAD

**Issue by yqs112358** [LipPkg/LipUI#11]
# TODOs总览
- [ ] 改进欢迎页面
- [ ] 转变LipUI的整体设计思想
- [ ] 修改主页页面设计
- [ ] 将其他页面进行适配

# 概述
LipUI其实是一个极好的利于新手上手的、有利于插件分发的重要机制，可以类比于Vue ui。因此我认为，对于LipUI来说最重要的就是
1. 如何清晰地向用户表述LipUI的设计目的
2. 如何引导用户快速熟悉相关机制和使用

针对这几点，目前LipUI仍然有一些细节上的不足，下面提出一些改进建议。
<br>

# 欢迎页面
针对问题1，我的建议是可以设计一个比较简单清晰的欢迎页面，代替现在的免责声明大页面。随手画了一点展示自己的想法，具体的UI设计排布有待讨论，这里只是随便举个例子：
<img src="https://user-images.githubusercontent.com/37969157/228299309-62f87c2e-f08e-4ee8-933d-60e078bd3e69.png" width="600px">
类似这种
<br>

# 主页设计和整体设计思想改进
目前的主页布局中只有比较简单的一个工作目录选取页面，个人对这里的设计不太满意。主页之所以为主页，最重要的就是在这里需要给用户一个关于此系统的总览性的内容展示，而LipUI在这方面还略有欠缺。
<img src="https://user-images.githubusercontent.com/37969157/228302210-e475221c-09da-43c7-a39e-2ef334144d06.png" width="600px">
可以看到这里只有一个工作目录选取的功能，可以增加、删除工作目录等。这个“工作目录”的概念其实在开发者群体中是较为熟知的，但是在普通用户很可能就不太熟悉这个概念。另外这里的整体设计略有冗杂，按钮较多，第一眼让人有些无从下手。

要想办法改进这一点，就要牵扯到目前LipUI的设计思想问题：由于LipUI目前本身的设计原则是基于**通用包管理器**进行服务，因此会有“工作目录”这种概念。不过在我看来，包管理器这种具有特定目的性的工具就应该有明确的设计和使用目标。Lip和LipUI最核心也是目前唯一的目的就是为LL、BDS和插件分发服务，就像npm之于nodejs，pip之于python。
因此，我建议有必要将整体的思路进行更改，调整为以BDS、LL为中心，以分发插件和依赖为主要功能的设计思想。
这一思路变更，展现在主页这里，就是将设计思路往类面板改动，将BDS和LL置于设计的核心之中，而不是所有的包都平等对待。这里我还没有特别成熟的UI设计思路，不过可以提供一种可能的选择（画的比较丑，不要在意细节，大概思路展示）：
<img src="https://user-images.githubusercontent.com/37969157/228308669-f55ce3fb-02ba-4226-8244-5cb0e972b7b0.png" width="800px">
在主页直接展示多个服务端。这一设计解决了之前讨论过的，LipUI只适合于管理单一服务端的问题。在主页展示此端安装的所有的包信息，并可以进入包市场选择新包进行安装。

同时，思路改变之后，也需要将Lip仓库中本来和其他插件等同地位的BDS和LL两者分离开来。在Lip端不需要进行改动，不过LipUI这里需要对此进行针对性的设计：
比如在刚刚的主页下方点击➕的时候，创建的就是纯净的BDS环境，在此基础上对插件包、addon进行配置安装等，而不是提供一个和其他包平齐的Starter Pack让用户去手动安装，这样对新手用户来说有些无从下手。

同时，其他部分菜单，如“本地包”“安装包”等也需要配合此思想进行一些改进。具体UI设计有待深入讨论

**Comment by LazuliKao** [comment]
在主页显示已安装的包是否有些重复，

**Comment by LazuliKao** [comment]
另外欢迎页面使用单独的窗体？还是对话框

**Comment by yqs112358** [comment]
可以再想想怎么设计，我这里只是随便提供个思路（

**Comment by yqs112358** [comment]
> 另外欢迎页面使用单独的窗体？还是对话框

看怎么实现方便把，单独窗体是不是比较好布局（？
