### ISSUE TITLE
支持i18n多语言

### ISSUE THREAD

**Issue by yqs112358** [LipPkg/LipUI#12]
如题，至少支持中英文双语

**Comment by LazuliKao** [comment]
![image](https://user-images.githubusercontent.com/46601807/229425732-ef833e84-91d9-4d24-a084-8b8388212c15.png)
多语言模块基本完成

添加更多语言到https://github.com/LiteLDev/LipUI/tree/develop/src/LipUI/Language

中文内置https://github.com/LiteLDev/LipUI/blob/develop/src/LipUI/Language/Model.cs

其他语言嵌入lang文件，如英语https://github.com/LiteLDev/LipUI/blob/develop/src/LipUI/Language/Files/en.lang
