### ISSUE TITLE
齿包安装过程中允许用户向右侧命令行输入

### ISSUE THREAD

**Issue by JunketPear** [LipPkg/LipUI#2]
---
如题
应允许用户在齿包安装过程中向右侧命令行输入指令
且对于安装进度条  放在搜索栏附近最佳
---
**以下是“无法处理confirmation”问题的反馈**
如题
在使用lip-ui下载BDS的时候
卡在99%
![image](https://user-images.githubusercontent.com/58849532/219872209-291f621a-9e7f-4a4b-bc2b-d99fca7c9236.png)
可以看到背后的日志里卡在了同意条款

复现方案
打开lip-ui  进入包市场  安装BDS 即可完美复现

解决方案
1.可以将安装进度放至安装页面内，而不是附在页面上，并在右方命令输出区加入输入框
2.可以监听输出内容，监听到“Do You Agree...”字样时弹出对话框 询问是否同意条款，若点击是，则向程序中输入“y”，反之亦然、
3.可以监听输出内容，监听到“Do You Agree...”字样时直接无脑输出y，无需询问

**Comment by LazuliKao** [comment]
已修改，目前是检测到(y/n)弹出对话框给用户，用户确认后自动模拟y输入
请测试actions

**Comment by LazuliKao** [comment]
直接允许命令行输入指令可能增加使用成本和复杂度，故仅保留最简UI界面，这个issue先关了
