### ISSUE TITLE
为registry.litebds.com提供镜像站能力

### ISSUE THREAD

**Issue by yqs112358** [lippkg/LipUI#21]
如题，梯子不开全局时LipUI无法加载索引
<img width="382" alt="image" src="https://user-images.githubusercontent.com/37969157/228312836-1943575c-9dd7-4a21-a763-e2bdb3a5df6c.png">

去中心化！去中心化！
至少设置国内国外两个index站，用某些办法保持两者同步，然后在Lip中内置此两个index地址。gh pages不定期会被墙或者干扰，国内无法稳定直连使用。

**Comment by futrime** [comment]
Registry没啦！
