### ISSUE TITLE
不能更新Lip包(ui和命令行都是)

### ISSUE THREAD

**Issue by USS-LongIsland** [LipPkg/LipUI#27]
我的操作:
关闭服务端 打开LipUI 选中想要升级的Lip包并点击升级 选择新版本安装
日志显示安装完成 后经查看发现包并没有被更新 使用命令行进入工作目录 操作如下

尝试清除缓存
PS C:\BDS\Server lip cache purge
Cache has been purged successfully.

PS C:\BDS\Server> lip install --upgrade ll
Validating specifiers...
  Validating ll...
Resolving dependencies and downloading tooths...
  Fetching github.com/tooth-hub/liteloaderbds@2.14.1...
    Already installed.
--upgrade flag is set, Lip will upgrade all installed tooths specified by the specifiers...
Uninstalling tooths to be reinstalled or upgraded...
Installing tooths...
Successfully installed all tooth files.

PS C:\BDS\Server> lip install --upgrade bds
Validating specifiers...
  Validating bds...
Resolving dependencies and downloading tooths...
  Fetching github.com/tooth-hub/bds@1.20.1...
    Already installed.
--upgrade flag is set, Lip will upgrade all installed tooths specified by the specifiers...
Uninstalling tooths to be reinstalled or upgraded...
Installing tooths...
Successfully installed all tooth files.

PS C:\BDS\Server> lip list
Tooth                              Version
---------------------------------- ----------
github.com/tooth-hub/bds           1.20.0
github.com/tooth-hub/bdsdownloader 0.3.1
github.com/tooth-hub/crashlogger   1.0.1
github.com/tooth-hub/liteloaderbds 2.14.0
github.com/tooth-hub/llanticheat   1.9.0
github.com/tooth-hub/llessentials  2.14.0
github.com/tooth-hub/peeditor      3.2.0

使用命令行也没有成功更新

**Comment by Futrime** [comment]
@USS-LongIsland lip版本多少

**Comment by LazuliKao** [comment]
可能是版本问题，lip用最新版本，lipui暂时用GitHub actions 的构建，应该没问题

**Comment by USS-LongIsland** [comment]
非常感谢 我的版本确实旧了 已经塞了新版本的lip 一会等服务端没人了我试试
